apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      imagePullSecrets:
      - name: nexus-secret
      containers:
      - name: node-app
        image: 3.229.134.81:5000/node-app:latest
        ports:
        - containerPort: 3000